# Generated by Django 4.1.3 on 2022-11-06 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='Емейл')),
                ('text', models.TextField(verbose_name='Сообщение')),
                ('delay', models.IntegerField(default=10, verbose_name='Время в секундах')),
                ('due_time', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Срок выполнения')),
            ],
        ),
    ]
